// flow-typed signature: 4a1cf54067f97b9f53b9e97bd2e54e3e
// flow-typed version: <<STUB>>/es-check_v^2.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'es-check/index' {
  declare module.exports: $Exports<'es-check'>;
}
declare module 'es-check/index.js' {
  declare module.exports: $Exports<'es-check'>;
}
