// flow-typed signature: 657b0080fffe57643b8c45e2a6a3e703
// flow-typed version: <<STUB>>/@integreat-app/eslint-config-node_v^0.3.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@integreat-app/eslint-config-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@integreat-app/eslint-config-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@integreat-app/eslint-config-node/index' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-node'>;
}
declare module '@integreat-app/eslint-config-node/index.js' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-node'>;
}
