export default {
  'United States': ['Adak', 'Pago Pago', 'Honolulu', 'Hilo', 'Anchorage',
    'Fairbanks', 'Sitka', 'Juneau', 'Adamstown', 'Portland', 'San Francisco',
    'Jacksonville', 'Charlotte', 'Miami', 'Pittsburgh', 'Buffalo', 'Raleigh',
    'Jamestown', 'Hagåtña', 'Dededo', 'Saipan', 'St. Louis', 'New York City'],
  Canada: ['Whitehorse', 'Vancouver', 'Yellowknife', 'Calgary', 'Edmonton',
    'Saskatoon', 'Regina', 'Winnipeg', 'Toronto', 'Ottawa', 'Montreal',
    'Iqaluit', 'Fredericton', 'Charlottetown', "St. John's", 'Quebec City',
    'City of Halifax'],
  Mexico: ['Tijuana', 'Mexicali', 'Chihuahua', 'Durango', 'Zapopan',
    'Guadalajara', 'Monterrey', 'Mexico City', 'Puebla', 'Veracruz', 'Mérida'],
  Chile: ['Hanga Roa', 'Valdivia', 'Concepción', 'Valparaíso', 'La Serena',
    'Punta Arenas', 'Santiago', 'Antofagasta', 'Iquique', 'Calama',
    'Puerto Williams'],
  Malaysia: ['George Town', 'Ipoh', 'Kuala Lumpur', 'Kota Bharu',
    'Johor Bahru', 'Kuching', 'Miri', 'Kota Kinabalu', 'Alor Star',
    'Malacca Town'],
  Brazil: ['Rio Branco', 'Porto Velho', 'Boa Vista', 'Manaus', 'Cuiabá',
    'Campo Grande', 'Chuí', 'Pelotas', 'Porto Alegre', 'Macapá', 'Curitiba',
    'Belém', 'Brasília', 'Campinas', 'São Paulo', 'Vitória', 'Ilhéus',
    'Fortaleza', 'Maceió', 'Recife', 'Praia', 'Porto', 'São Tomé', 'Bern',
    'São José dos Campos', 'Rio de Janeiro'],
  Argentina: ['Mendoza', 'Ushuaia', 'Córdoba', 'Bahía Blanca', 'Rosario',
    'Buenos Aires', 'San Carlos de Bariloche', 'Ciudad del Este'],
  Italy: ['Assis', 'Turin', 'Milan', 'Rome', 'Naples'],
  Portugal: ['Ponta Delgada', 'Lisbon', 'Horta (Azores)',
    'Angra do Heroísmo'],
  Morocco: ['Casablanca', 'Rabat', 'Marrakech'],
  Spain: ['Seville', 'Málaga', 'Madrid', 'Bilbao', 'Valencia', 'Ibiza',
    'Barcelona', 'Palma', 'Santa Cruz de Tenerife',
    'Las Palmas de Gran Canaria'],
  'United Kingdom': ['Belfast', 'Glasgow', 'Cardiff', 'Edinburgh', 'Liverpool',
    'Manchester', 'Aberdeen', 'Birmingham', 'Leeds', 'London', 'Greenwich',
    'Newcastle'],
  Australia: ['Douglas', 'Mandurah', 'Perth', 'Port Hedland', 'Darwin',
    'Adelaide', 'Geelong', 'Melbourne', 'Cairns', 'Townsville', 'Hobart',
    'Canberra', 'Rockhampton', 'Wollongong', 'Sydney', 'Brisbane',
    'Gold Coast'],
  France: ['Nantes', 'Toulouse', 'Paris', 'Lyon', 'Marseille', 'Cannes',
    'Nice', 'Strasbourg'],
  Nigeria: ['Lagos', 'Ibadan', 'Abuja', 'Enugu', 'Kano'],
  Netherlands: ['The Hague', 'Rotterdam', 'Amsterdam'],
  Germany: ['Düsseldorf', 'Cologne', 'Frankfurt', 'Stuttgart', 'Hanover',
    'Hamburg', 'Munich', 'Leipzig', 'Berlin', 'Dresden'],
  'South Africa': ['Cape Town', 'Port Elizabeth', 'Bloemfontein',
    'Johannesburg', 'Pretoria', 'Durban'],
  Poland: ['Kraków', 'Warsaw', 'Gdańsk'],
  Russia: ['Kaliningrad', 'Saint Petersburg', 'Murmansk', 'Moscow', 'Samara',
    'Perm', 'Yekaterinburg', 'Omsk', 'Novosibirsk', 'Norilsk', 'Bratsk',
    'Yakutsk', 'Vladivostok', 'Magadan', 'Nizhny Novgorod',
    'Petropavlovsk-Kamchatsky'],
  Greece: ['Athens', 'Thessaloniki'],
  Ukraine: ['Lviv', 'Odessa', 'Simferopol', 'Kharkiv', 'Kiev'],
  Turkey: ['Istanbul', 'Bursa', 'Konya', 'Ankara', 'Mersin', 'Adana',
    'Gaziantep', 'İzmir'],
  Egypt: ['Alexandria', 'Cairo', 'Port Said', 'Suez', 'Luxor'],
  Swaziland: ['Mbabane', 'Lobamba', 'Manzini'],
  Tanzania: ['Mwanza', 'Dodoma', 'Zanzibar City', 'Dar es Salaam'],
  'Saudi Arabia': ['Jeddah', 'Medina', 'Mecca', 'Riyadh', 'Dammam'],
  Pakistan: ['Karachi', 'Multan', 'Peshawar', 'Faisalabad', 'Rawalpindi',
    'Islamabad', 'Lahore'],
  India: ['Hyderabad', 'Ahmedabad', 'Mumbai', 'Surat', 'Pune', 'Srinagar',
    'Amritsar', 'Jaipur', 'Ludhiana', 'New Delhi', 'Bangalore', 'Nagpur',
    'Chennai', 'Kanpur', 'Lucknow', 'Patna', 'Gangtok', 'Agartala', 'Guwahati',
    'Shillong', 'Port Blair', 'Dibrugarh', 'Kolkata'],
  'Sri Lanka': ['Colombo', 'Kandy', 'Batticaloa', 'Sri Jayawardenapura-Kotte'],
  China: ['Ürümqi', 'Shigatse', 'Lhasa', 'Xining', 'Kunming', 'Lanzhou',
    'Chengdu', 'Chongqing', 'Nanning', 'Taiyuan', 'Guangzhou', 'Zhengzhou',
    'Dongguan', 'Shenzhen', 'Wuhan', 'Handan', 'Shijiazhuang', 'Beijing',
    'Jinan', 'Tianjin', 'Nanjing', 'Hangzhou', 'Qingdao', 'Shanghai', 'Dalian',
    'Shenyang', 'Changchun', 'Harbin', "Xi'an"],
  Indonesia: ['Banda Aceh', 'Medan', 'Padang', 'Pekanbaru', 'Palembang',
    'Jakarta', 'Bogor', 'Bandung', 'Pontianak', 'Semarang', 'Malang',
    'Surabaya', 'Denpasar', 'Balikpapan', 'Makassar', 'Ambon', 'Jayapura',
    'Yogyakarta (city)'],
  Thailand: ['Chiang Mai', 'Surat Thani', 'Hat Yai', 'Bangkok', 'Pattaya',
    'Nakhon Ratchasima', 'Udon Thani', 'Phuket (city)'],
  Vietnam: ['Hanoi', 'Hai Phong', 'Ho Chi Minh City', 'Da Nang', 'Huế'],
  'South Korea': ['Incheon', 'Seoul', 'Daegu', 'Busan'],
  Japan: ['Okinawa', 'Fukuoka', 'Hiroshima', 'Kobe', 'Osaka', 'Kyoto',
    'Nagoya', 'Yokohama', 'Kawasaki', 'Sapporo', 'Tokyo'],
  'New Zealand': ['Invercargill', 'Dunedin', 'Christchurch', 'Wellington',
    'Auckland']
} as const
